#!/usr/bin/perl

#BEGIN_HEADER
#
# Module Parse/Easy/Lexer/OpCodes.pm Copyright (C) 2018 Mahdi Safsafi.
#
# https://github.com/MahdiSafsafi/Parse-Easy
#
# See licence file 'LICENCE' for use and distribution rights.
#
#END_HEADER

#################################################
# automatically generated file. do not edit !!! #
#################################################

package Parse::Easy::Lexer::OpCodes;
use strict;
use warnings;
use base qw(Exporter);
our @EXPORT_OK = qw(instructions);

my @instructions = (
  {
    args      => ["uimm8"],
    immediate => 0,
    maxsize   => 1,
    mnem      => "db",
    patterns  => ["u8"],
    relative  => 0,
  },
  {
    args      => ["uimm16"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "dw",
    patterns  => ["u16"],
    relative  => 0,
  },
  {
    args      => ["uimm32"],
    immediate => 0,
    maxsize   => 4,
    mnem      => "dd",
    patterns  => ["u32"],
    relative  => 0,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 0,
    mnem      => "label",
    patterns  => [],
    relative  => 0,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 1,
    mnem      => "vmstart",
    patterns  => ["0x00"],
    relative  => 0,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 1,
    mnem      => "vmend",
    patterns  => ["0x01"],
    relative  => 0,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "call",
    patterns  => ["0x02", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "call",
    patterns  => ["0x03", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "call",
    patterns  => ["0x04", "od"],
    relative  => 1,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "b",
    patterns  => ["0x05", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "b",
    patterns  => ["0x06", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "b",
    patterns  => ["0x07", "od"],
    relative  => 1,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "beq",
    patterns  => ["0x08", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "beq",
    patterns  => ["0x09", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "beq",
    patterns  => ["0x0a", "od"],
    relative  => 1,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "bneq",
    patterns  => ["0x0b", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "bneq",
    patterns  => ["0x0c", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "bneq",
    patterns  => ["0x0d", "od"],
    relative  => 1,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "bgt",
    patterns  => ["0x0e", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "bgt",
    patterns  => ["0x0f", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "bgt",
    patterns  => ["0x10", "od"],
    relative  => 1,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "bge",
    patterns  => ["0x11", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "bge",
    patterns  => ["0x12", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "bge",
    patterns  => ["0x13", "od"],
    relative  => 1,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "blt",
    patterns  => ["0x14", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "blt",
    patterns  => ["0x15", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "blt",
    patterns  => ["0x16", "od"],
    relative  => 1,
  },
  {
    args      => ["rel8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "ble",
    patterns  => ["0x17", "ob"],
    relative  => 1,
  },
  {
    args      => ["rel16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "ble",
    patterns  => ["0x18", "ow"],
    relative  => 1,
  },
  {
    args      => ["rel32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "ble",
    patterns  => ["0x19", "od"],
    relative  => 1,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 1,
    mnem      => "nop",
    patterns  => ["0x1a"],
    relative  => 0,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 1,
    mnem      => "peek",
    patterns  => ["0x1b"],
    relative  => 0,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 1,
    mnem      => "advance",
    patterns  => ["0x1c"],
    relative  => 0,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 1,
    mnem      => "forget",
    patterns  => ["0x1d"],
    relative  => 0,
  },
  {
    args      => [],
    immediate => 0,
    maxsize   => 1,
    mnem      => "ret",
    patterns  => ["0x1e"],
    relative  => 0,
  },
  {
    args      => ["uimm32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "setstate",
    patterns  => ["0x23", "u32"],
    relative  => 0,
  },
  {
    args      => ["imm8"],
    immediate => 1,
    maxsize   => 2,
    mnem      => "mark",
    patterns  => ["0x24", "i8"],
    relative  => 0,
  },
  {
    args      => ["imm16"],
    immediate => 1,
    maxsize   => 3,
    mnem      => "mark",
    patterns  => ["0x25", "i16"],
    relative  => 0,
  },
  {
    args      => ["imm32"],
    immediate => 1,
    maxsize   => 5,
    mnem      => "mark",
    patterns  => ["0x26", "i32"],
    relative  => 0,
  },
  {
    args      => ["r0", "uimm8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "cmp",
    patterns  => ["0x27", "u8"],
    relative  => 0,
  },
  {
    args      => ["r0", "uimm16"],
    immediate => 0,
    maxsize   => 3,
    mnem      => "cmp",
    patterns  => ["0x28", "u16"],
    relative  => 0,
  },
  {
    args      => ["r0", "uimm32"],
    immediate => 0,
    maxsize   => 5,
    mnem      => "cmp",
    patterns  => ["0x29", "u32"],
    relative  => 0,
  },
  {
    args      => ["rr", "offset"],
    immediate => 0,
    maxsize   => 6,
    mnem      => "inrange",
    patterns  => ["0x2a", "mf"],
    relative  => 0,
  },
  {
    args      => ["imm8"],
    immediate => 1,
    maxsize   => 2,
    mnem      => "isatx",
    patterns  => ["0x2b", "i8"],
    relative  => 0,
  },
  {
    alias     => 1,
    args      => [],
    immediate => 0,
    maxsize   => 2,
    mnem      => "ststart",
    patterns  => ["0x30", "0x00"],
    relative  => 0,
  },
  {
    alias     => 1,
    args      => [],
    immediate => 0,
    maxsize   => 2,
    mnem      => "stend",
    patterns  => ["0x30", "0x01"],
    relative  => 0,
  },
  {
    args      => ["uimm8"],
    immediate => 0,
    maxsize   => 2,
    mnem      => "hint",
    patterns  => ["0x30", "u8"],
    relative  => 0,
  },
);

sub instructions { \@instructions }

1;
